baseurl = "/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # "light" or "dark"
  defaultTheme = "dark"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4

  # Show reading time in minutes for posts
  showReadingTime = true

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  # toc = true

  # Show full page content in RSS feed items
  #(default is Description or Summary metadata in the front matter)
  # rssFullText = true

[taxonomies]
  # Use singular rather than plural for default taxonomies
  tag = "tag"
  category = "category"

[languages]
  [languages.en]
    title = "Hello Jacob"
    subtitle = "A collection of Jacob's random thoughts and stuff"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by Jacob"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer"
    olderPosts = "Older"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.en.params.logo]
      logoText = "hello jacob"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "category"
        name = "Category"
        url = "/category"
